services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" 
    depends_on:
      - db
    networks:
      - mynetwork
    environment:
      SERVER_ADDRESS: zadanie-6105.avito2024.codenrock.com:8080
      POSTGRES_CONN: postgres://postgres:rew12345@db:5432/avitotestdbname?sslmode=disable
      POSTGRES_JDBC_URL: jdbc:postgresql://db:5432/avitotestdbname
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: rew12345
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: avitotestdbname
    env_file:
      - .env

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rew12345
      POSTGRES_DB: avitotestdbname
    ports:
      - "5432:5432" 
    volumes:
      - /docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data  
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge 

volumes:
  postgres-data:
    driver: local  
